Feat: Added bugs

diff --git a/linux-autohost b/linux-autohost
--- a/linux-autohost
+++ b/linux-autohost
@@ -12,13 +12,18 @@ if [ "$EUID" -ne 0 ]; then
   	exit
 fi
 
+if ([ $(cat /etc/*-release | grep ID=debian) != "" ] || ([ $(cat /etc/*-release | grep ID=debian) = "" ] && [ $(cat /etc/*-release | grep ID_LIKE=debian) != "" ])) ;then
+	echo -e "\e[31mError \e[39m: This script isn't accessible for non-debian based distribution."
+  	exit
+fi
+
 if [[ $(dpkg --get-selections | grep apache2) = "" ]] ;then
-	echo -e "\e[31mError \e[39m: You need to install \e[33mapache2\e[39m using \e[33msudo apt-get install apache2\e[39m"
+	echo -e "\e[31mError \e[39m: You need to install \e[33mapache2\e[39m using \e[33msudo apt-get install apache2\e[39m."
   	exit
 fi
 
 if [[ $(dpkg --get-selections | grep mysql-server) = "" ]] ;then
-	echo -e "\e[31mError \e[39m: You need to install \e[33mmysql-server\e[39m using \e[33msudo apt-get install mysql-server\e[39m"
+	echo -e "\e[31mError \e[39m: You need to install \e[33mmysql-server\e[39m using \e[33msudo apt-get install mysql-server\e[39m."
   	exit
 fi
 
